### ISSUE TITLE
Ruby constants

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/oo-basics#14]
had not learned or heard about Ruby constants but was expected to understand them in this lab

User: Kevin McCormack

Batch: teacher-fellowship-1015

Current Lesson: Instance Methods Lab

Location: https://learn.co/tracks/teacher-training-web-development-fundamentals/ruby-fundamentals/beginning-object-orientation/bringing-it-together?track_id=11897&batch_id=288

Bug Description: So the spec test 01_book_spec.rb wants a constant defined as `GENRES = ["Thriller", "Science Fiction", "Romance"]` but this is not talked about at all in the lesson or any before it that I am doing on Learn for the teacher fellowship. I had to get the information from a Google search. http://rubylearning.com/satishtalim/ruby_constants.html

**Comment by AnnJohn** [comment]
Closing this issue actually since constants are covered before in the Full Stack track, and I can add that content to the Teacher fellowship.
