### ISSUE TITLE
Post-Program Qualifying Track Lesson

### ISSUE THREAD

**Issue by yoshikot** [learn-co-curriculum/oo-basics#16]
After completing the Program Qualifying Track (Tic-Tac-Toe) for the Learn Verified Full Stack Program and playing around with a few Euler lessons, the first lesson I was “thrown into” was Object Lifecycle -> OO Basics. By the time I tried OO School Domain it became evident that there were lessons on Hashes, all the way back in Procedural Ruby that wasn’t a part of the Program Qualifying Track. So right now I’m going back to Procedural Ruby lessons that I haven’t completed yet. This does not seem like the appropriate place for a person in my position to begin their program after the Tic-Tac-Toe track since we've skipped a few concepts.

**Comment by AnnJohn** [comment]
Hi @yoshikot apologies for the delay with this. The Full Stack track actually starts with Git/ Github and continues to HTML/CSS and then to Ruby. There are early Ruby lessons in the Full Stack track that you already completed in the Qualifying Track but the majority of the content is brand new. 

Sorry again for the confusion.
