### ISSUE TITLE
#countdown_with_sleep only checks for time spent in method, not actual completion of task

### ISSUE THREAD

**Issue by Sillhouette** [learn-co-curriculum/oo-basics#30]
The method #countdown_with_sleep only checks if it takes the allotted amount of time to run the method but nothing else. This means you could hack the tests by simply putting sleep(5) into the method and it will pass the tests. 

This defeats the purpose of the task and should be fixed accordingly as some students are thinking they are doing whats asked of them by only calling sleep(5) for that method.

**Comment by Sillhouette** [comment]
It also runs the check if(time >= 5 seconds) or whatever which means if you put sleep(any number above 1) it will pass the tests and not be the correct answer

**Comment by drakeltheryuujin** [comment]
Hi @Sillhouette,

Did you open an issue on the wrong lesson? I don't see see any methods with this information in the README or tests.

Closing the issue on this lesson as it doesn't seem to be on topic.

Thanks for contributing! 💙
